# Generated by Django 5.1.6 on 2025-10-04 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_alter_educationalvideo_description_videorequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_bounce_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_delivered_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_drop_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_last_event_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_spam_report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_email_event',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_email_event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('unsubscribed', 'Unsubscribed'), ('complained', 'Complained'), ('stored', 'Stored'), ('other', 'Other')], max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('mg_message_id', models.CharField(blank=True, help_text='Mailgun message ID', max_length=255)),
                ('mg_event_id', models.CharField(blank=True, help_text='Mailgun event ID', max_length=255)),
                ('event_data', models.JSONField(default=dict, help_text='Raw JSON data received from Mailgun webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email'], name='web_emailev_email_a8e6a7_idx'), models.Index(fields=['event_type'], name='web_emailev_event_t_02108b_idx'), models.Index(fields=['timestamp'], name='web_emailev_timesta_37604b_idx'), models.Index(fields=['mg_message_id'], name='web_emailev_mg_mess_c45fcd_idx'), models.Index(fields=['email', 'timestamp'], name='web_emailev_email_time_idx'), models.Index(fields=['email', 'event_type'], name='web_emailev_email_event_idx')],
            },
        ),
    ]
