# Generated by Django 5.1.6 on 2025-10-14 15:35

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0062_update_waitingroom_for_sessions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Campaign title", max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", markdownx.models.MarkdownxField(help_text="Detailed description of the campaign")),
                (
                    "funding_goal",
                    models.DecimalField(decimal_places=2, help_text="Target amount to raise", max_digits=10),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Amount raised so far", max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "budget_breakdown",
                    models.TextField(blank=True, help_text="Itemized budget showing how funds will be used"),
                ),
                ("video_url", models.URLField(blank=True, help_text="Optional video pitch URL")),
                ("deadline", models.DateField(blank=True, help_text="Campaign deadline", null=True)),
                ("school_name", models.CharField(blank=True, help_text="School or institution name", max_length=200)),
                (
                    "school_verified",
                    models.BooleanField(default=False, help_text="Whether school identity is verified"),
                ),
                ("matching_enabled", models.BooleanField(default=False, help_text="Enable matching grants")),
                (
                    "matching_multiplier",
                    models.DecimalField(
                        decimal_places=1, default=1.0, help_text="Matching multiplier (e.g., 2.0 for 2x match)", max_digits=3
                    ),
                ),
                (
                    "matching_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Maximum matching amount", max_digits=10, null=True
                    ),
                ),
                ("matching_sponsor", models.CharField(blank=True, help_text="Name of matching sponsor", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(help_text="Campaign image", upload_to="campaign_images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False, help_text="Set as campaign cover image")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="web.campaign"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignDonation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("message", models.TextField(blank=True, help_text="Message from donor")),
                ("anonymous", models.BooleanField(default=False)),
                ("stripe_payment_intent_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="donations", to="web.campaign"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("content", markdownx.models.MarkdownxField(help_text="Update content")),
                ("image", models.ImageField(blank=True, help_text="Optional update image", upload_to="campaign_updates/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="updates", to="web.campaign"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
