# Generated by Django 5.1.6 on 2025-10-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0062_update_waitingroom_for_sessions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Competition title", max_length=200)),
                ("description", models.TextField(help_text="Detailed description of the competition")),
                ("start_date", models.DateTimeField(help_text="When the competition starts")),
                ("end_date", models.DateTimeField(help_text="When the competition ends")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("archived", "Archived"),
                        ],
                        default="upcoming",
                        max_length=10,
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of participants (leave blank for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "entry_fee_points",
                    models.PositiveIntegerField(
                        default=0, help_text="Points required to enter the competition (0 for free)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, help_text="Competition banner image", null=True, upload_to="competition_images/"
                    ),
                ),
                ("rules", models.TextField(blank=True, help_text="Competition rules and guidelines")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenges",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Challenges included in this competition",
                        related_name="competitions",
                        to="web.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["status", "start_date"], name="web_competi_status_9f7e44_idx"),
                    models.Index(fields=["end_date"], name="web_competi_end_dat_e1c7fa_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompetitionReward",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("scholarship", "Scholarship"),
                            ("premium_subscription", "Premium Subscription"),
                            ("merchandise", "Merchandise"),
                            ("points", "Points"),
                            ("badge", "Badge"),
                            ("certificate", "Certificate"),
                            ("goods", "Store Goods"),
                        ],
                        max_length=25,
                    ),
                ),
                ("name", models.CharField(help_text="Reward name (e.g., '$500 Scholarship')", max_length=200)),
                ("description", models.TextField(help_text="Detailed description of the reward")),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Required position/rank to win this reward (1 for 1st place)"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, help_text="Number of this reward available")),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monetary value (for scholarships)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "points_amount",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of points awarded (for point rewards)", null=True
                    ),
                ),
                (
                    "subscription_months",
                    models.PositiveIntegerField(
                        blank=True, help_text="Subscription duration in months (for premium subscriptions)", null=True
                    ),
                ),
                ("is_awarded", models.BooleanField(default=False, help_text="Whether this reward has been awarded")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rewards", to="web.competition"
                    ),
                ),
                (
                    "goods_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Store item to award (for merchandise)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.goods",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "competition"],
                "unique_together": {("competition", "position")},
            },
        ),
        migrations.CreateModel(
            name="CompetitionParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveIntegerField(default=0, help_text="Cumulative score in this competition")),
                (
                    "rank",
                    models.PositiveIntegerField(blank=True, help_text="Current rank in the competition", null=True),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_submission_at",
                    models.DateTimeField(blank=True, help_text="Last time user submitted a challenge", null=True),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="web.competition"
                    ),
                ),
                (
                    "rewards_claimed",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Rewards this participant has claimed",
                        related_name="recipients",
                        to="web.competitionreward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "joined_at"],
                "unique_together": {("competition", "user")},
                "indexes": [
                    models.Index(fields=["competition", "-score"], name="web_competi_competi_e3a0c5_idx"),
                    models.Index(fields=["user", "-joined_at"], name="web_competi_user_id_4f3f81_idx"),
                ],
            },
        ),
    ]
