# Generated by Django 5.1.6 on 2025-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0063_massclasspoll_massclasspolloption_massclassstream_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="youtube_stream_key",
            field=models.CharField(blank=True, help_text="Your YouTube Live stream key for broadcasting", max_length=100),
        ),
    ]
