# Generated by Django 5.1.15 on 2026-02-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_virtualclassroom_virtualclassroomcustomization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
